/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/ErrorsIT.p.vm.java
 */
package fr.vendredi.web.selenium;

import org.junit.Test;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import fr.vendredi.web.selenium.page.role.RoleSearchPage;

import fr.vendredi.web.selenium.support.SeleniumTest;
import fr.vendredi.web.selenium.page.HomePage;
import fr.vendredi.web.selenium.support.Page;

public class ErrorsIT extends SeleniumTest {
    @Test
    public void invalidLoginOrPassword() {
        englishHomePage();
        webClient.step("Login as unknown_user, and verify it is not valid");
        anonymousHomePage.connexion();
        loginPage.login("unknownUser", "invalidPassword");
        loginPage.hasMessage("Invalid credentials");
    }

    RoleSearchPage roleSearchPage;

    @Test
    public void dataIntegrityError() {
        englishHomePage();
        loginAsAnAdmin();
        loggedHomePage.roles();
        roleSearchPage.delete("ROLE_ADMIN");
        roleSearchPage.hasMessage("Action refused because it violates data integrity");
    }

    @Page
    public static class AjaxErrors extends HomePage {
        @FindBy(id = "form:debug_button")
        public WebElement debugButton;
        @FindBy(id = "form:throwException")
        public WebElement throwException;
        @FindBy(id = "form:throwAjaxException")
        public WebElement throwAjaxException;
        @FindBy(id = "form:throwDataAccessException")
        public WebElement throwDataAccessException;
        @FindBy(id = "form:thowAjaxDataAccessException")
        public WebElement throwAjaxDataAccessException;
    }

    AjaxErrors ajaxErrors;

    @Test
    public void catchException() {
        englishHomePage();
        webClient.click(ajaxErrors.debugButton);
        webClient.click(ajaxErrors.throwException);
        ajaxErrors.hasMessage("Just testing RuntimeException from ExceptionUtil");
        webClient.click(ajaxErrors.debugButton);
        webClient.click(ajaxErrors.throwAjaxException);
        ajaxErrors.hasMessage("Just testing RuntimeException from ExceptionUtil");
    }

    @Test
    public void catchDataException() {
        englishHomePage();
        webClient.click(ajaxErrors.debugButton);
        webClient.click(ajaxErrors.throwDataAccessException);
        ajaxErrors.hasMessage("We have detected a concurrent modification");
        webClient.click(ajaxErrors.debugButton);
        webClient.click(ajaxErrors.throwAjaxDataAccessException);
        ajaxErrors.hasMessage("We have detected a concurrent modification");
    }
}
